// <auto-generated />
namespace DbHander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _06082017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_06082017));
        
        string IMigrationMetadata.Id
        {
            get { return "201708061618066_06-08-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
