// <auto-generated />
namespace DbHander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _05122017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_05122017));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051341414_05-12-2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
