// <auto-generated />
namespace DbHander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180713 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180713));
        
        string IMigrationMetadata.Id
        {
            get { return "201807131700569_2018-07-13"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
