// <auto-generated />
namespace DbHander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1503201802 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1503201802));
        
        string IMigrationMetadata.Id
        {
            get { return "201803152254396_15-03-2018-02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
