// <auto-generated />
namespace DbHander.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _27012018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_27012018));
        
        string IMigrationMetadata.Id
        {
            get { return "201801271425353_27-01-2018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
