//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobInit.ProcSessionManagementService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcSessionInfo", Namespace="http://schemas.datacontract.org/2004/07/BLW.DataAccessService.DataContract")]
    [System.SerializableAttribute()]
    public partial class ProcSessionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ExpectedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool KillRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProcComponentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RunningJobIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Created {
            get {
                return this.CreatedField;
            }
            set {
                if ((this.CreatedField.Equals(value) != true)) {
                    this.CreatedField = value;
                    this.RaisePropertyChanged("Created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ExpectedDateTime {
            get {
                return this.ExpectedDateTimeField;
            }
            set {
                if ((this.ExpectedDateTimeField.Equals(value) != true)) {
                    this.ExpectedDateTimeField = value;
                    this.RaisePropertyChanged("ExpectedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool KillRequired {
            get {
                return this.KillRequiredField;
            }
            set {
                if ((this.KillRequiredField.Equals(value) != true)) {
                    this.KillRequiredField = value;
                    this.RaisePropertyChanged("KillRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProcComponentID {
            get {
                return this.ProcComponentIDField;
            }
            set {
                if ((this.ProcComponentIDField.Equals(value) != true)) {
                    this.ProcComponentIDField = value;
                    this.RaisePropertyChanged("ProcComponentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessID {
            get {
                return this.ProcessIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessIDField, value) != true)) {
                    this.ProcessIDField = value;
                    this.RaisePropertyChanged("ProcessID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RunningJobID {
            get {
                return this.RunningJobIDField;
            }
            set {
                if ((this.RunningJobIDField.Equals(value) != true)) {
                    this.RunningJobIDField = value;
                    this.RaisePropertyChanged("RunningJobID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionKey {
            get {
                return this.SessionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionKeyField, value) != true)) {
                    this.SessionKeyField = value;
                    this.RaisePropertyChanged("SessionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcSessionManagementService.IProcSessionManagementService")]
    public interface IProcSessionManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcSessionManagementService/GetAllUnusedProcess", ReplyAction="http://tempuri.org/IProcSessionManagementService/GetAllUnusedProcessResponse")]
        JobInit.ProcSessionManagementService.ProcSessionInfo[] GetAllUnusedProcess();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcSessionManagementService/DeleteProcSession", ReplyAction="http://tempuri.org/IProcSessionManagementService/DeleteProcSessionResponse")]
        bool DeleteProcSession(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcSessionManagementService/UpdateBySessionKey", ReplyAction="http://tempuri.org/IProcSessionManagementService/UpdateBySessionKeyResponse")]
        bool UpdateBySessionKey(string sessionKey, byte status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcSessionManagementServiceChannel : JobInit.ProcSessionManagementService.IProcSessionManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcSessionManagementServiceClient : System.ServiceModel.ClientBase<JobInit.ProcSessionManagementService.IProcSessionManagementService>, JobInit.ProcSessionManagementService.IProcSessionManagementService {
        
        public ProcSessionManagementServiceClient() {
        }
        
        public ProcSessionManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcSessionManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcSessionManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcSessionManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JobInit.ProcSessionManagementService.ProcSessionInfo[] GetAllUnusedProcess() {
            return base.Channel.GetAllUnusedProcess();
        }
        
        public bool DeleteProcSession(int id) {
            return base.Channel.DeleteProcSession(id);
        }
        
        public bool UpdateBySessionKey(string sessionKey, byte status) {
            return base.Channel.UpdateBySessionKey(sessionKey, status);
        }
    }
}
